language: r
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

jobs:
  include:
    - r: oldrel
    - r: release
      before_script:
        - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
      before_cache:
        - Rscript -e 'xfun::pkg_load2("covr")'
      after_success:
        - Rscript -e 'covr::codecov()'
        - "(curl -L https://xran.yihui.org/r-xran | bash)"
    - r: devel
      env: _R_CHECK_CRAN_INCOMING_=true
